---
- hosts: localhost
  connection: local
  tasks:
  - name: "Install required software"
    apt:
      name: "{{ packages }}"
      state: present
    become: true
    vars:
      packages:
        - python3-pip
        - docker
        - docker-compose
  - name: "Starting Docker"
    become: true
    service:
      name: docker
      state: started
      enabled: yes
  - name: "Pull git repo"
    git:
      repo: git@github.com:OthomDev/VagrantTest.git
      dest: /tmp/embedded-tomcat-spring/
      version: master
